/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyApplicationsRouteImport } from './routes/my-applications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminCreateJobRouteImport } from './routes/admin.create-job'
import { Route as JobsJobIdRouteImport } from './routes/jobs_.$jobId'
import { Route as AdminEditJobJobIdRouteImport } from './routes/admin.edit-job.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApplicationsRoute = MyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateJobRoute = AdminCreateJobRouteImport.update({
  id: '/admin/create-job',
  path: '/admin/create-job',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs_/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditJobJobIdRoute = AdminEditJobJobIdRouteImport.update({
  id: '/admin/edit-job/$jobId',
  path: '/admin/edit-job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/my-applications': typeof MyApplicationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/create-job': typeof AdminCreateJobRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/admin/edit-job/$jobId': typeof AdminEditJobJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/my-applications': typeof MyApplicationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/create-job': typeof AdminCreateJobRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/admin/edit-job/$jobId': typeof AdminEditJobJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/my-applications': typeof MyApplicationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/create-job': typeof AdminCreateJobRoute
  '/jobs_/$jobId': typeof JobsJobIdRoute
  '/admin/edit-job/$jobId': typeof AdminEditJobJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/login'
    | '/my-applications'
    | '/profile'
    | '/register'
    | '/admin/create-job'
    | '/jobs/$jobId'
    | '/admin/edit-job/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/login'
    | '/my-applications'
    | '/profile'
    | '/register'
    | '/admin/create-job'
    | '/jobs/$jobId'
    | '/admin/edit-job/$jobId'
  id:
    | '__root__'
    | '/'
    | '/jobs'
    | '/login'
    | '/my-applications'
    | '/profile'
    | '/register'
    | '/admin/create-job'
    | '/jobs_/$jobId'
    | '/admin/edit-job/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  MyApplicationsRoute: typeof MyApplicationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  AdminCreateJobRoute: typeof AdminCreateJobRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  AdminEditJobJobIdRoute: typeof AdminEditJobJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-applications': {
      id: '/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof MyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-job': {
      id: '/admin/create-job'
      path: '/admin/create-job'
      fullPath: '/admin/create-job'
      preLoaderRoute: typeof AdminCreateJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs_/$jobId': {
      id: '/jobs_/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edit-job/$jobId': {
      id: '/admin/edit-job/$jobId'
      path: '/admin/edit-job/$jobId'
      fullPath: '/admin/edit-job/$jobId'
      preLoaderRoute: typeof AdminEditJobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  MyApplicationsRoute: MyApplicationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  AdminCreateJobRoute: AdminCreateJobRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  AdminEditJobJobIdRoute: AdminEditJobJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
